import Link from "next/link";
import { ArrowLeft, CalendarDays, Leaf, MapPin } from "lucide-react";
import { notFound } from "next/navigation";
import PrintButton from "@/components/PrintButton";
import { farmExperiences } from "@/data/farmExperiences";

export function generateStaticParams() {
  return farmExperiences.map((experience) => ({ slug: experience.slug }));
}

export default async function ExperienceSheetPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const experience = farmExperiences.find((item) => item.slug === slug);

  if (!experience) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-[#faf8f5] pb-12 text-[#2c3f16]">
      <div className="no-print sticky top-0 z-50 w-full border-b border-[#b7c6ad]/40 bg-[#f3f8ef]/90 py-4 shadow-sm backdrop-blur-md">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6">
          <Link href={`/products/${experience.slug}`} className="inline-flex items-center gap-2 text-sm font-semibold hover:text-[#806018]">
            <ArrowLeft className="h-4 w-4" /> Back to experience
          </Link>
          <div className="flex items-center gap-4">
            <span className="text-xs text-[#48624a]">Demo field guide preview</span>
            <PrintButton />
          </div>
        </div>
      </div>

      <article className="print-container mx-auto mt-8 max-w-3xl rounded-sm border border-[#b7c6ad]/30 bg-white p-8 shadow-xl md:p-14">
        <header className="border-b border-[#b7c6ad]/50 pb-6 text-center">
          <p className="text-xs font-semibold uppercase tracking-[0.4em] text-[#2c3f16]">ROOT & RISE · DEMO FIELD GUIDE</p>
          <div className="mx-auto mt-3 h-[1.5px] w-32 bg-[#a67c1c]" />
          <p className="mt-5 text-xs font-bold uppercase tracking-[0.22em] text-[#a67c1c]">Agro-tourism frontend project</p>
          <h1 className="mt-3 font-serif-display text-4xl text-[#2c3f16]">{experience.title}</h1>
          <p className="mx-auto mt-3 max-w-2xl text-sm leading-relaxed text-[#48624a]">{experience.description}</p>
        </header>

        <section className="mt-8 grid gap-3 sm:grid-cols-3">
          <div className="rounded-xl bg-[#edf4e8] p-4"><MapPin className="h-5 w-5 text-[#a67c1c]" /><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-[#48624a]">Location</p><p className="mt-1 text-sm">{experience.location}</p></div>
          <div className="rounded-xl bg-[#edf4e8] p-4"><CalendarDays className="h-5 w-5 text-[#a67c1c]" /><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-[#48624a]">Duration</p><p className="mt-1 text-sm">{experience.duration}</p></div>
          <div className="rounded-xl bg-[#edf4e8] p-4"><Leaf className="h-5 w-5 text-[#a67c1c]" /><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-[#48624a]">Indicative price</p><p className="mt-1 text-sm">{experience.price}</p></div>
        </section>

        <section className="mt-8">
          <h2 className="border-b border-[#b7c6ad]/40 bg-[#edf4e8]/85 px-4 py-2 text-xs font-semibold uppercase tracking-widest">What the visit includes</h2>
          <ul className="mt-4 space-y-3 pl-6 text-sm leading-relaxed text-[#48624a]">
            {experience.highlights.map((highlight) => <li key={highlight} className="list-disc">{highlight}</li>)}
          </ul>
        </section>

        <section className="mt-8">
          <h2 className="border-b border-[#b7c6ad]/40 bg-[#edf4e8]/85 px-4 py-2 text-xs font-semibold uppercase tracking-widest">Community and sustainability note</h2>
          <p className="mt-4 text-sm leading-relaxed text-[#48624a]">{experience.impact}</p>
        </section>

        <section className="mt-8 rounded-xl bg-[#20351b] p-5 text-sm leading-relaxed text-[#d8d2c4]">
          <p className="font-semibold text-[#f7f3ec]">College-project disclaimer</p>
          <p className="mt-2">This field guide is a frontend demonstration. Availability, payments, inventory, and host verification would be added in a future production version.</p>
        </section>

        <footer className="mt-10 flex justify-between border-t border-[#b7c6ad]/30 pt-4 text-[10px] text-[#7f976f]">
          <span>Generated by Root & Rise</span>
          <span>Demo field guide</span>
        </footer>
      </article>

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body { background: white !important; color: black !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .no-print { display: none !important; }
          .print-container { margin: 0 !important; border: none !important; box-shadow: none !important; max-width: none !important; }
        }
      ` }} />
    </div>
  );
}
